"""Alembic migrations script template"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ab1c639166'
down_revision = '68039e7bd76d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
