"""Alembic migrations script template"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2cfc2fbe79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'SOLD', 'INVESTED', name='propertystatus'), nullable=False),
    sa.Column('image_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('area_sqft', sa.Float(), nullable=True),
    sa.Column('expected_roi', sa.Float(), nullable=True),
    sa.Column('total_fractions', sa.Integer(), nullable=True),
    sa.Column('fraction_price', sa.Float(), nullable=True),
    sa.Column('project_value', sa.Float(), nullable=True),
    sa.Column('fractions_sold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('PUBLIC', 'USER', 'INVESTOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('investment_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('investment_amount', sa.Float(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_applications_id'), 'investment_applications', ['id'], unique=False)
    op.create_index(op.f('ix_investment_applications_status'), 'investment_applications', ['status'], unique=False)
    op.create_index(op.f('ix_investment_applications_user_id'), 'investment_applications', ['user_id'], unique=False)
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('fractions_owned', sa.Integer(), nullable=True),
    sa.Column('initial_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_id'), 'investments', ['id'], unique=False)
    op.create_table('property_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'CLOSED', name='inquirystatus'), nullable=False),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_admin_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_inquiries_email'), 'property_inquiries', ['email'], unique=False)
    op.create_index(op.f('ix_property_inquiries_id'), 'property_inquiries', ['id'], unique=False)
    op.create_index(op.f('ix_property_inquiries_status'), 'property_inquiries', ['status'], unique=False)
    op.create_index(op.f('ix_property_inquiries_user_id'), 'property_inquiries', ['user_id'], unique=False)
    op.create_table('property_occupancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('nights_booked', sa.Integer(), nullable=False),
    sa.Column('nights_available', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_occupancy_id'), 'property_occupancy', ['id'], unique=False)
    op.create_table('property_revenue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('gross_revenue', sa.Float(), nullable=False),
    sa.Column('expenses', sa.Float(), nullable=False),
    sa.Column('distributed', sa.Boolean(), nullable=False),
    sa.Column('distribution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_revenue_id'), 'property_revenue', ['id'], unique=False)
    op.create_table('updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_updates_id'), 'updates', ['id'], unique=False)
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('notify_on_update', sa.Boolean(), nullable=False),
    sa.Column('notify_on_price_change', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', name='unique_user_property_wishlist')
    )
    op.create_index(op.f('ix_wishlist_id'), 'wishlist', ['id'], unique=False)
    op.create_index(op.f('ix_wishlist_property_id'), 'wishlist', ['property_id'], unique=False)
    op.create_index(op.f('ix_wishlist_user_id'), 'wishlist', ['user_id'], unique=False)
    op.create_table('earnings_distribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_revenue_id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('fractions_owned', sa.Integer(), nullable=False),
    sa.Column('ownership_percentage', sa.Float(), nullable=False),
    sa.Column('earnings_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='distributionstatus'), nullable=False),
    sa.Column('paid_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_revenue_id'], ['property_revenue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earnings_distribution_id'), 'earnings_distribution', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earnings_distribution_id'), table_name='earnings_distribution')
    op.drop_table('earnings_distribution')
    op.drop_index(op.f('ix_wishlist_user_id'), table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_property_id'), table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_id'), table_name='wishlist')
    op.drop_table('wishlist')
    op.drop_index(op.f('ix_updates_id'), table_name='updates')
    op.drop_table('updates')
    op.drop_index(op.f('ix_property_revenue_id'), table_name='property_revenue')
    op.drop_table('property_revenue')
    op.drop_index(op.f('ix_property_occupancy_id'), table_name='property_occupancy')
    op.drop_table('property_occupancy')
    op.drop_index(op.f('ix_property_inquiries_user_id'), table_name='property_inquiries')
    op.drop_index(op.f('ix_property_inquiries_status'), table_name='property_inquiries')
    op.drop_index(op.f('ix_property_inquiries_id'), table_name='property_inquiries')
    op.drop_index(op.f('ix_property_inquiries_email'), table_name='property_inquiries')
    op.drop_table('property_inquiries')
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_investment_applications_user_id'), table_name='investment_applications')
    op.drop_index(op.f('ix_investment_applications_status'), table_name='investment_applications')
    op.drop_index(op.f('ix_investment_applications_id'), table_name='investment_applications')
    op.drop_table('investment_applications')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
